### ISSUE TITLE
Add documentation for already parsed documents

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/birdcage#3]
People will want to run this pipeline without the part that runs CoreNLP, because they may have already parsed the text (as we have at OU) and just want to run the event coder and geolocation. The documentation should specify clearly:

1. the format the articles should be stored in the SQLite DB (is this this same as the example JSON)?
2. How to put the articles into SQLite, if we assume they have the parsed text stored in Mongo.

**Comment by solaimani** [comment]
I took the JSON example from SQLiteDB. 
Do you want me to write a MongoDB reader in parallel to SQLiteDB reader?

**Comment by solaimani** [comment]
Added mongo to sqlitedb converter in commit 58deefd. We can't read from mongodb because when we do database pagging, mongodb applies skip which is expensive. We can't use "id" (similar format in Biryani's corenlp output) because it is not an integer. Moreover, converting is more generic and we found that sqlite's batch insertion is really fast.

**Comment by ahalterman** [comment]
That looks great. If SQLite is way faster and the work of going from Mongo to SQLite is basically hidden from the user, that seems like a good way to do it.
